### ISSUE TITLE
Feature request: allow keeping the socials and disqus at the bottom of chapters

### ISSUE THREAD

**Issue by megamorphg** [TagoDR/MangaOnlineViewer#265]
Would it be possible to have an option to to keep the socials (comments) at the bottom of chapters? Sometimes this is nice

**Comment by big-cat-loaf** [comment]
I would recommend putting a disqus.com frame in the bottom of the chapters.

**Comment by TagoDR** [comment]
I've added a comments area, may look horrible it depends on how they configured their Disqus, I'm just reusing what was in the page, there is nothing I can do yet, please test it.

**Comment by big-cat-loaf** [comment]
doesn't look that bad 
![Screenshot 2023-06-19 151435](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/b16e3aea-745d-4aee-ab80-4ac5cfa17cf7)

**Comment by TagoDR** [comment]
Sure, if adblokers doesn't remove it.
same problem with appearance, cant change it, to be nice you would need to flip to light mode

**Comment by big-cat-loaf** [comment]
Well I disagree because of amount of annoyances that some websits have at the bottem of the page is unbelavible like: mangaread.org: 
![Screenshot 2023-06-20 174300](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/1c8e9a98-add8-47d5-9314-9bfa77952cca)
![Screenshot 2023-06-20 174320](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/bb4c8ebc-84f9-46dc-a4a1-347992cb90ec)

**Comment by TagoDR** [comment]
A universal rule is only possible if all sites use the same structure, which they don't. Disqus and Facebook are possible because they are a **standardized** external site, meaning I can just reuse the existing iframe and that section of the site should still work fine.
I erase the site completely after extracting all the data I need to completely remake the sites, to be as safe as possible against ADs, links, redirects and key binds. Even then, it is still not 100% in some sites.


I'm now to detecting the color scheme required by that area and setting it there, should be readable now.
As far as I can see, most sites with comment sections are scalators, and they mostly use disqus, for now I'm satisfied with this solution which works with most cases.
