### ISSUE TITLE
won't start loading from where I want to look

### ISSUE THREAD

**Issue by kakarisu** [TagoDR/MangaOnlineViewer#267]
I'm using Adult Reader(Default Load Mode : always) ,

which loads from the beginning every time, which is not very convenient.

For example there are 200 pages of manga, I press page 100 and it still loads from the beginning

**Comment by TagoDR** [comment]
yes that the expected behavior. I need to ignore witch page you are on,you need to explicitly tell the script with page to start using a bookmark or change the  Load mode to never(or ask, and cancel), you have to click to load and there you'll have the option to actualy choose witch page to start reading
