### ISSUE TITLE
(Site Request) INKR

### ISSUE THREAD

**Issue by omodia** [TagoDR/MangaOnlineViewer#295]
### I trust this will be helpful.
Manhua - [Apocalypse Online, Chapter 1](https://comics.inkr.com/title/1075-apocalypse-online?ref=search)

    The images here are masked with /t.jpg at the end of the image link. The image is 100 x 224.
    The next image is only loaded after scrolling down, then '/t.jpg' is changed to '/p.jpg'.
    It has a resolution of 850 x 1275 and of jpg format.

https://user-images.githubusercontent.com/116664905/215994364-14183f60-f47d-4277-b20f-4a0319579cad.mp4

**Comment by TagoDR** [comment]
Added, check it out

**Comment by TagoDR** [comment]
The bug is because there are some stubborn scripts they use that keeps trying to do something and falling because I have erased their target in the page. There is nothing I can do, other than forcing a longer wait before starting.
Downloading chapters is just bonus, not the main goal of the script, you better of finding a scrapper tool for that, a good one will manage it better without causing a DDOS attack to the site.
