### ISSUE TITLE
visortmo.com/TuMangaOnline doesn't work

### ISSUE THREAD

**Issue by duradara** [TagoDR/MangaOnlineViewer#413]
Example link: https://visortmo.com/viewer/af92d46353c7f4e38b7a439d6d63e1f3/cascade 
When you open the link the script seems like its working but then it closes and nothing happens. 
![Screenshot 2024-01-20 111215](https://github.com/TagoDR/MangaOnlineViewer/assets/50158352/00aae13a-6326-4e73-84b4-38d2f9c939c3)
![2](https://github.com/TagoDR/MangaOnlineViewer/assets/50158352/3a5ac6d1-6ebf-47c4-99b6-e3372ca64e43)

I am using Edge Version 120.0.2210.144 (Official build) (64-bit) and also tried on Firefox 121.0.1 (64-bit)
and the userscript version is 2024.01.19

**Comment by big-cat-loaf** [comment]
I tested your new script, and for other websites, a new bug occurred since the comments must be loaded to activate the script, but since the same website only loads the comments when you come near the button, you must scroll to the button to activate the script. My fix would be that the script starts in a preacctivate state, scrolls to the bottom, and then acctivates fully.
Edit: It seems that https://www.mgeko.com/ doesn't care for the comments specifically but only the bottom of the page, which means that when you just ignore the rule that the website needs the comments to load, it automatically loads when you reach the bottom of the page.

Url: https://www.mgeko.com/
one example:
https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/1ceacc62-0efe-40d1-a8d6-f61524ed3df8 
(copy of #411)

**Comment by TagoDR** [comment]
Fixed, I've added a timeout
