### ISSUE TITLE
[Feature request] better Bookmarks

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#426]
I want a button that only bookmarks the specific web page I'm on, like a one-click safe. 
The thing is that for the best experience, I recommend hiding the user control, and there is no way to save the bookmarks with it on. 
I would appreciate a butten that is next to the "Go to Page" butten.

BUG: The delete button doesn't work for Bookmarks!!

**Comment by TagoDR** [comment]
Bug fixed. 
I have added a button to save the current page in the bookmark list

The bookmark is supposed to be  a way to remember where you stopped reading, to quickly resume. So much so that I set it to auto erase after opening it, its temporary.
The browser have a permanent bookmark, and you can save/sync with multiple services.
To Save one image you better off just saving it to your hd.
